= Enhancing HubPress Documentation

:published_at: 2015-03-23
:hp-tags: team, presentation
:url-jared-github: http://github.com/jaredmorgs/
:url-jared-hubpress: http://jaredmorgs.github.io/
:url-jared-youtube: https://youtu.be/KoaGU91qJv8
:url-jared-photo: https://cloud.githubusercontent.com/assets/2006548/6719598/f3cd999e-cdbb-11e4-94fc-b7aed239452c.jpg
:url-readme: https://github.com/HubPress/hubpress.io/blob/master/README.adoc
:url-john: https://github.com/johncarl81
:url-jaq: https://github.com/asciidoctor/jekyll-asciidoc-quickstart
:url-docs-bug: https://github.com/HubPress/hubpress.io/issues/153

AIDL 文件的说明

支持的数据类型

基本数据类型

List，仅ArrayList

Map，仅HashMap..

Parcelable，所有实现了Parcelable接口的对象

AIDL，所有的AIDL接口本身可以再AIDL文件中使用

Parcelable和AIDL对象在使用时，必须显式的import进来，不管是否存在于一个包中。

在aidl文件中使用自定义的Parcelable对象，必须新建一个和该对象同名的AIDL文件，并声明为parcelable。

除了基本类型，其他类型都必须标上方向：in、out、inout

aidl的包结构在服务端和客户端应该保持一致，否则无法解析AIDL 文件的说明

支持的数据类型

基本数据类型

List，仅ArrayList

Map，仅HashMap..

Parcelable，所有实现了Parcelable接口的对象

AIDL，所有的AIDL接口本身可以再AIDL文件中使用

Parcelable和AIDL对象在使用时，必须显式的import进来，不管是否存在于一个包中。

在aidl文件中使用自定义的Parcelable对象，必须新建一个和该对象同名的AIDL文件，并声明为parcelable。

除了基本类型，其他类型都必须标上方向：in、out、inout

aidl的包结构在服务端和客户端应该保持一致，否则无法解析AIDL 文件的说明

支持的数据类型

基本数据类型

List，仅ArrayList

Map，仅HashMap..

Parcelable，所有实现了Parcelable接口的对象

AIDL，所有的AIDL接口本身可以再AIDL文件中使用

Parcelable和AIDL对象在使用时，必须显式的import进来，不管是否存在于一个包中。

在aidl文件中使用自定义的Parcelable对象，必须新建一个和该对象同名的AIDL文件，并声明为parcelable。

除了基本类型，其他类型都必须标上方向：in、out、inout

aidl的包结构在服务端和客户端应该保持一致，否则无法解析AIDL 文件的说明

支持的数据类型

基本数据类型

List，仅ArrayList

Map，仅HashMap..

Parcelable，所有实现了Parcelable接口的对象

AIDL，所有的AIDL接口本身可以再AIDL文件中使用

Parcelable和AIDL对象在使用时，必须显式的import进来，不管是否存在于一个包中。

在aidl文件中使用自定义的Parcelable对象，必须新建一个和该对象同名的AIDL文件，并声明为parcelable。

除了基本类型，其他类型都必须标上方向：in、out、inout

aidl的包结构在服务端和客户端应该保持一致，否则无法解析